=== SamJoan/droopescan____old/data/vuln.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="stringtype">
    <xs:restriction base="xs:string">
      <xs:whiteSpace value="preserve" />
      <xs:minLength value="1" />
      <xs:pattern value="[^\s].+[^\s]|[^\s]"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="inttype">
    <xs:restriction base="xs:positiveInteger" />
  </xs:simpleType>

  <xs:simpleType name="uritype">
    <xs:restriction base="xs:anyURI">
      <xs:minLength value="1" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="cvetype">
    <xs:restriction base="xs:token">
      <xs:pattern value="[0-9]{4}-[0-9]{4,}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="typetype">
    <xs:restriction base="stringtype">
      <xs:enumeration value="SQLI"/>
      <xs:enumeration value="MULTI"/>
      <xs:enumeration value="REDIRECT"/>
      <xs:enumeration value="RCE"/>
      <xs:enumeration value="RFI"/>
      <xs:enumeration value="LFI"/>
      <xs:enumeration value="UPLOAD"/>
      <xs:enumeration value="UNKNOWN"/>
      <xs:enumeration value="XSS"/>
      <xs:enumeration value="CSRF"/>
      <xs:enumeration value="SSRF"/>
      <xs:enumeration value="AUTHBYPASS"/>
      <xs:enumeration value="BYPASS"/>
      <xs:enumeration value="FPD"/>
      <xs:enumeration value="XXE"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="itemtype">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="vulnerability" type="vulntype" />
    </xs:sequence>
    <xs:attribute type="stringtype" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="wordpresstype">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="vulnerability" type="vulntype"/>
    </xs:sequence>
    <xs:attribute type="stringtype" name="version" use="required"/>
  </xs:complexType>

  <xs:complexType name="vulntype">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:choice>
        <xs:element name="title" type="stringtype"/>
        <xs:element name="type" type="typetype"/>
        <xs:element name="fixed_in" type="stringtype"/>
        <xs:element name="references" type="referencetype"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="referencetype">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:choice>
        <xs:element name="url" type="uritype" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="cve" type="cvetype" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="secunia" type="inttype" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="osvdb" type="inttype" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="metasploit" type="stringtype" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="exploitdb" type="inttype" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="vulnerabilities">
    <xs:complexType>
      <xs:choice>
        <xs:element name="plugin" type="itemtype" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element name="theme" type="itemtype" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element name="wordpress" type="wordpresstype" maxOccurs="unbounded" minOccurs="0"/>
      </xs:choice>
    </xs:complexType>
    <xs:unique name="uniquePlugin">
      <xs:selector xpath="plugin"/>
      <xs:field xpath="@name"/>
    </xs:unique>
    <xs:unique name="uniqueTheme">
      <xs:selector xpath="theme"/>
      <xs:field xpath="@name"/>
    </xs:unique>
    <xs:unique name="uniqueWordpress">
      <xs:selector xpath="wordpress"/>
      <xs:field xpath="@version"/>
    </xs:unique>
  </xs:element>

</xs:schema>

=== SamJoan/droopescan____old/data/theme_vulns.xml
<?xml version="1.0" encoding="UTF-8"?>

<vulnerabilities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="vuln.xsd">

  <theme name="crius">
    <vulnerability>
      <title>VideoJS Cross-Site Scripting Vulnerability</title>
      <references>
        <secunia>53427</secunia>
        <url>http://seclists.org/fulldisclosure/2013/May/77</url>
      </references>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="source">
    <vulnerability>
      <title>VideoJS Cross-Site Scripting Vulnerability</title>
      <references>
        <secunia>53457</secunia>
        <url>http://seclists.org/fulldisclosure/2013/May/77</url>
      </references>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="i-love-it">
    <vulnerability>
      <title>VideoJS Cross-Site Scripting Vulnerability</title>
      <references>
        <secunia>53548</secunia>
        <url>http://seclists.org/fulldisclosure/2013/May/77</url>
      </references>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="smartstart">
    <vulnerability>
      <title>VideoJS Cross-Site Scripting Vulnerability</title>
      <references>
        <secunia>53460</secunia>
        <url>http://seclists.org/fulldisclosure/2013/May/77</url>
      </references>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="covertvideopress">
    <vulnerability>
      <title>VideoJS Cross-Site Scripting Vulnerability</title>
      <references>
        <secunia>53494</secunia>
        <url>http://seclists.org/fulldisclosure/2013/May/77</url>
      </references>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="photolio">
    <vulnerability>
      <title>VideoJS Cross-Site Scripting Vulnerability</title>
      <references>
        <url>http://seclists.org/fulldisclosure/2013/May/77</url>
      </references>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="onepagewebsite">
    <vulnerability>
      <title>onepagewebsite Full Path Disclosure vulnerability</title>
      <references>
        <url>http://1337day.com/exploit/20027</url>
      </references>
      <type>FPD</type>
    </vulnerability>
  </theme>

  <theme name="vithy">
    <vulnerability>
      <title>vithy - Full Path Disclosure vulnerability</title>
      <references>
        <url>http://1337day.com/exploit/20040</url>
      </references>
      <type>FPD</type>
    </vulnerability>
    <vulnerability>
      <title>vithy - Arbitrary File Upload Vulnerability</title>
      <references>
        <url>http://1337day.com/exploit/19830</url>
      </references>
      <type>UPLOAD</type>
    </vulnerability>
    <vulnerability>
      <title>vithy - Custom Background Shell Upload</title>
      <references>
        <url>http://packetstormsecurity.com/files/125827/</url>
      </references>
      <type>UPLOAD</type>
    </vulnerability>
  </theme>

  <theme name="appius">
    <vulnerability>
      <title>appius - Full Path Disclosure vulnerability</title>
      <references>
        <url>http://1337day.com/exploit/20039</url>
      </references>
      <type>FPD</type>
    </vulnerability>
    <vulnerability>
      <title>appius - Arbitrary File Upload Vulnerability</title>
      <references>
        <url>http://1337day.com/exploit/19831</url>
      </references>
      <type>UPLOAD</type>
    </vulnerability>
    <vulnerability>
      <title>appius - Custom Background Shell Upload</title>
      <references>
        <url>http://packetstormsecurity.com/files/125827/</url>
      </references>
      <type>UPLOAD</type>
    </vulnerability>
  </theme>

  <theme name="yvora">
    <vulnerability>
      <title>yvora - Full Path Disclosure vulnerability</title>
      <references>
        <url>http://1337day.com/exploit/20038</url>
      </references>
      <type>FPD</type>
    </vulnerability>
    <vulnerability>
      <title>yvora - Arbitrary File Upload Vulnerability</title>
      <references>
        <url>http://1337day.com/exploit/19834</url>
      </references>
      <type>UPLOAD</type>
    </vulnerability>
  </theme>

  <theme name="shotzz">
    <vulnerability>
      <title>Shotzz - Full Path Disclosure vulnerability</title>
      <references>
        <url>http://1337day.com/exploit/20041</url>
      </references>
      <type>FPD</type>
    </vulnerability>
    <vulnerability>
      <title>Shotzz - Arbitrary File Upload Vulnerability</title>
      <references>
        <url>http://1337day.com/exploit/19829</url>
      </references>
      <type>UPLOAD</type>
    </vulnerability>
    <vulnerability>
      <title>Shotzz - Custom Background Shell Upload</title>
      <references>
        <url>http://packetstormsecurity.com/files/125827/</url>
      </references>
      <type>UPLOAD</type>
    </vulnerability>
  </theme>

  <theme name="dagda">
    <vulnerability>
      <title>dagda - Arbitrary File Upload Vulnerability</title>
      <references>
        <url>http://1337day.com/exploit/19832</url>
      </references>
      <type>UPLOAD</type>
    </vulnerability>
    <vulnerability>
      <title>dagda - Custom Background Shell Upload</title>
      <references>
        <url>http://packetstormsecurity.com/files/125827/</url>
      </references>
      <type>UPLOAD</type>
    </vulnerability>
  </theme>

  <theme name="moneymasters">
    <vulnerability>
      <title>moneymasters - Full Path Disclosure vulnerability</title>
      <references>
        <url>http://1337day.com/exploit/20077</url>
      </references>
      <type>FPD</type>
    </vulnerability>
    <vulnerability>
      <title>moneymasters - File Upload Vulnerability (metasploit)</title>
      <references>
        <url>http://1337day.com/exploit/20076</url>
      </references>
      <type>UPLOAD</type>
    </vulnerability>
  </theme>

  <theme name="ovum">
    <vulnerability>
      <title>XSS vulnerability in Imediapixel premium WordPress themes</title>
      <references>
        <url>http://jannefi.blogspot.fi/2012/10/xss-vulnerability-in-imediapixel.html</url>
      </references>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="avanix">
    <vulnerability>
      <title>XSS vulnerability in Imediapixel premium WordPress themes</title>
      <references>
        <url>http://jannefi.blogspot.fi/2012/10/xss-vulnerability-in-imediapixel.html</url>
      </references>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="ebiz">
    <vulnerability>
      <title>XSS vulnerability in Imediapixel premium WordPress themes</title>
      <references>
        <url>http://jannefi.blogspot.fi/2012/10/xss-vulnerability-in-imediapixel.html</url>
      </references>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="ecobiz">
    <vulnerability>
      <title>XSS vulnerability in Imediapixel premium WordPress themes</title>
      <references>
        <url>http://jannefi.blogspot.fi/2012/10/xss-vulnerability-in-imediapixel.html</url>
      </references>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="traject">
    <vulnerability>
      <title>XSS vulnerability in Parallelus premium WordPress themes</title>
      <references>
        <url>http://jannefi.blogspot.fi/2012/10/xss-vulnerability-in-parallelus-premium.html</url>
      </references>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="intersect">
    <vulnerability>
      <title>XSS vulnerability in Parallelus premium WordPress themes</title>
      <references>
        <url>http://jannefi.blogspot.fi/2012/10/xss-vulnerability-in-parallelus-premium.html</url>
      </references>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="salutation">
    <vulnerability>
      <title>XSS vulnerability in Parallelus premium WordPress themes</title>
      <references>
        <url>http://jannefi.blogspot.fi/2012/10/xss-vulnerability-in-parallelus-premium.html</url>
      </references>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="unite">
    <vulnerability>
      <title>XSS vulnerability in Parallelus premium WordPress themes</title>
      <references>
        <url>http://jannefi.blogspot.fi/2012/10/xss-vulnerability-in-parallelus-premium.html</url>
      </references>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="shapeless">
    <vulnerability>
      <title>Shapeless - Unspecified XSS</title>
      <references>
        <osvdb>85919</osvdb>
        <url>http://jannefi.blogspot.fi/2012/09/xss-vulnerability-in-multiple-premium.html</url>
      </references>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="brisk">
    <vulnerability>
      <title>Brisk - Unspecified XSS</title>
      <references>
        <osvdb>85918</osvdb>
        <url>http://jannefi.blogspot.fi/2012/09/xss-vulnerability-in-multiple-premium.html</url>
      </references>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="blaze">
    <vulnerability>
      <title>Blaze - Unspecified XSS</title>
      <references>
        <osvdb>85917</osvdb>
        <url>http://jannefi.blogspot.fi/2012/09/xss-vulnerability-in-multiple-premium.html</url>
      </references>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="eunice">
    <vulnerability>
      <title>Eunice - Unspecified XSS</title>
      <references>
        <osvdb>85916</osvdb>
        <url>http://jannefi.blogspot.fi/2012/09/xss-vulnerability-in-multiple-premium.html</url>
      </references>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="explicit">
    <vulnerability>
      <title>Explicit - Unspecified XSS</title>
      <references>
        <osvdb>85915</osvdb>
        <url>http://jannefi.blogspot.fi/2012/09/xss-vulnerability-in-multiple-premium.html</url>
      </references>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="essence">
    <vulnerability>
      <title>Essence - Unspecified XSS</title>
